// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package entry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.Config
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	ModuleName           string   `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Event                string   `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Level                string   `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Request              []byte   `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`
	Response             []byte   `protobuf:"bytes,7,opt,name=response,proto3" json:"response,omitempty"`
	ErrorText            string   `protobuf:"bytes,8,opt,name=errorText,proto3" json:"errorText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Entry) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Entry) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Entry) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Entry) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Entry) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Entry) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Entry) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func init() {
	proto.RegisterType((*Entry)(nil), "entry.Entry")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_daa6c5b6c627940f) }

var fileDescriptor_daa6c5b6c627940f = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbd, 0xaa, 0xc2, 0x40,
	0x10, 0x85, 0xd9, 0x7b, 0xb3, 0xf9, 0x99, 0x7b, 0xab, 0xc1, 0x62, 0x10, 0x91, 0x60, 0x95, 0xca,
	0xc6, 0x67, 0xb0, 0xb5, 0x08, 0xbe, 0x80, 0xe2, 0x80, 0x42, 0x92, 0x8d, 0xbb, 0x93, 0xa0, 0x4f,
	0xe9, 0x2b, 0xc9, 0x4e, 0xf0, 0xa7, 0x3b, 0xdf, 0x77, 0x38, 0x03, 0x03, 0x7f, 0xdc, 0x89, 0xbf,
	0xaf, 0x7b, 0xef, 0xc4, 0xa1, 0x55, 0x58, 0x3d, 0x0c, 0xd8, 0x6d, 0x4c, 0xb8, 0x04, 0x68, 0xdd,
	0x69, 0x68, 0x78, 0x77, 0x68, 0x99, 0x4c, 0x69, 0xaa, 0xa2, 0xfe, 0x32, 0x88, 0x90, 0x9c, 0x5d,
	0x10, 0xfa, 0xd1, 0x46, 0x33, 0xce, 0xc0, 0xf2, 0xc8, 0x9d, 0xd0, 0xaf, 0xca, 0x09, 0xa2, 0x6d,
	0x78, 0xe4, 0x86, 0x92, 0xc9, 0x2a, 0xc4, 0xbd, 0x5c, 0x5a, 0x26, 0x3b, 0xed, 0x63, 0x46, 0x82,
	0xcc, 0xf3, 0x75, 0xe0, 0x20, 0x94, 0x96, 0xa6, 0xfa, 0xaf, 0x5f, 0x88, 0x73, 0xc8, 0x3d, 0x87,
	0xde, 0x75, 0x81, 0x29, 0xd3, 0xea, 0xcd, 0xb8, 0x80, 0x82, 0xbd, 0x77, 0x7e, 0xcf, 0x37, 0xa1,
	0x5c, 0xcf, 0x7d, 0xc4, 0x31, 0xd5, 0xff, 0x36, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0x58,
	0x75, 0x2f, 0xee, 0x00, 0x00, 0x00,
}
